# Site settings
title: My github page
email: danielknoell@gmx.de
description: > # this means to ignore newlines until "baseurl:"
  This is my example page for playing around with github and Jekyll :)
github_username:  danny4927
highlighter: true
github: [Repository metadata]

# Build settings
markdown: kramdown
permalink: pretty