# Site settings
title:  Daniels Homepage
email: info@danielknoell.de
description: > # this means to ignore newlines until "baseurl:"
  Die private Homepage mit kleinem Tech Blog von Daniel Knöll. Hier erfahrt ihr alles über mich. Angefangen von meinem Lebenslauf über ein paar technische Beiträge zu verschiedensten Themen bis zu meinen bisherigen Veröffentlichungen.
github_username:  danny4927
author: Daniel Knöll
publisher: Daniel Knöll
url: https://danielknoell.de
highlighter: rouge
github: [Repository metadata]
isso:
  data_isso: //comments.danielknoell.de/
  script_src: //comments.danielknoell.de/js/embed.min.js

#htmlproofer
html_proofer:
  ssl_verifyhost: 0

hyphenate_filter:
  language: de_de
  left: 2
  right: 2
  hyphen: "&shy;"

# Build settings
exclude: [vendor]
markdown: kramdown
permalink: pretty
encoding: utf-8
languages: ["de"]
#seo
lang:       de_DE

srcset:
  cache: "/tmp/images"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-srcset
#  - jekyll-hyphenate_filter