# Site settings
title: Daniel Knöll
email: info@danielknoell.de
description: > # this means to ignore newlines until "baseurl:"
  Die private Homepage mit kleinem Tech Blog von Daniel Knöll.
github_username:  danny4927
author: Daniel Knöll
url: https://danielknoell.de
highlighter: rouge
github: [Repository metadata]
isso:
  data_isso: https://comments.danielknoell.de/
  script_src: https://comments.danielknoell.de/js/embed.min.js

# Build settings
exclude: [vendor]
markdown: kramdown
permalink: pretty
encoding: utf-8
languages: ["de"]
srcset:
  optipng: true
  cache: "/tmp/images"
gems:
  - jekyll-seo-tag
  - jekyll-sitemap