# Site settings
title: My Site
email: danielknoell@gmx.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username:  danny4927
highlighter: pygments
github: [Repository metadata]

# Build settings
markdown: kramdown
