# Site settings
title: My github page
email: danielknoell@gmx.de
description: > # this means to ignore newlines until "baseurl:"
  This is my example page for playing around with github and Jekyll :)
github_username:  danny4927
highlighter: rouge
github: [Repository metadata]
isso:
  data_isso: https://comments.danielknoell.de/
  script_src: https://comments.danielknoell.de/js/embed.min.js

# Build settings
exclude: [vendor]
markdown: kramdown
permalink: pretty
encoding: utf-8